[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/builders/server"
  status = 200

[functions]
  external_node_modules = ["@prisma/client", ".prisma/client"]
