[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", ".prisma/client"]

# For SPA fallback if needed
[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

